services:
  # 1. MongoDB Database Service
  mongodb:
    image: mongo:latest
    container_name: mern-mongodb
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: securepassword
    volumes:
      - mongo-data:/data/db

  # 2. Node.js Express Backend Service
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: mern-backend
    ports:
      - "4000:4000"
    environment:
      - MONGODB_URI=mongodb://admin:securepassword@mongodb:27017/food_db?authSource=admin
      - PORT=4000
      - JWT_SECRET=YGvykuiR0te7HPbBt0rESBS2wvZLYQSxl9oLOQLEdtr
    depends_on:
      - mongodb

  # 3. Vite Frontend Service
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: mern-frontend
    ports:
      - "5173:5173"
    environment:
      - VITE_HOST=0.0.0.0
      - VITE_PORT=5173 
      - VITE_PROXY_TARGET=http://backend:4000
    depends_on:
      - backend

  # 4. Admin Page
  admin:
    build:
      context: ./admin
      dockerfile: Dockerfile
    container_name: mern-admin
    ports:
      - "5174:5174"
    environment:
      - VITE_HOST=0.0.0.0
      - VITE_PORT=5174
      - VITE_PROXY_TARGET=http://backend:4000
    depends_on:
      - backend

# Persistent volume so you don't lose data when the database container stops
volumes:
  mongo-data:
