apiVersion: v1
kind: Secret
metadata:
  name: mongodb-secret
  namespace: default
type: Opaque
data:
  # data for base64 encoded, stringData for literal string.
  username: YWRtaW4= #admin
  password: cGFzc3dvcmQ= #password
  db: bXktbW9uZ28tZGF0YWJhc2U= #my-mongo-database
  jwtsecret: WUd2eWt1aVIwdGU3SFBiQnQwckVTQlMyd3ZaTFlRU3hsOW9MT1FMRWR0cg== # YGvykuiR0te7HPbBt0rESBS2wvZLYQSxl9oLOQLEdtr
